CREATE OR REPLACE PROCEDURE "REFRESH_TRANSFORMS"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    -- ---- Silver orders (unchanged) ----
    CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDERS_SILVER AS
    SELECT
        RAW_JSON:guid::STRING AS ORDER_GUID, RAW_JSON:restaurantGuid::STRING AS RESTAURANT_GUID,
        CONVERT_TIMEZONE(''UTC'',''America/New_York'', TRY_TO_TIMESTAMP_NTZ(RAW_JSON:paidDate::STRING,''YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM''))::DATE AS BUSINESS_DATE,
        TRY_TO_TIMESTAMP_NTZ(RAW_JSON:openedDate::STRING,''YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'') AS OPENED_DATE,
        TRY_TO_TIMESTAMP_NTZ(RAW_JSON:closedDate::STRING,''YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'') AS CLOSED_DATE,
        TRY_TO_TIMESTAMP_NTZ(RAW_JSON:paidDate::STRING,''YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM'') AS PAID_DATE,
        RAW_JSON:displayNumber::STRING AS DISPLAY_NUMBER, RAW_JSON:source::STRING AS SOURCE,
        RAW_JSON:approvalStatus::STRING AS APPROVAL_STATUS,
        RAW_JSON:voided::BOOLEAN AS VOIDED, RAW_JSON:deleted::BOOLEAN AS DELETED,
        RAW_JSON:diningOption:guid::STRING AS DINING_OPTION_GUID, RAW_JSON:diningOption:name::STRING AS DINING_OPTION_NAME,
        RAW_JSON:checks[0]:totalAmount::FLOAT AS TOTAL_AMOUNT,
        RAW_JSON:checks[0]:taxAmount::FLOAT AS TAX_AMOUNT,
        RAW_JSON:checks[0]:totalAmount::FLOAT - COALESCE(RAW_JSON:checks[0]:taxAmount::FLOAT,0) AS SUBTOTAL_AMOUNT,
        -- NET_AMOUNT = Toast "Net Sales" = SUM of non-voided checks'' `amount` (post-discount, pre-tax,
        -- tip-excluded, void-excluded) MINUS deferred-revenue selections (gift-card sells/reloads,
        -- selectionType TOAST_CARD_RELOAD/TOAST_CARD_SELL/GIFTCARD) which Toast excludes from Net Sales.
        -- Uses array REDUCE (scalar subquery errors inside CTAS). Matches Toast to the penny; 2026-07-03.
        REDUCE(
          FILTER(RAW_JSON:checks, c -> NOT COALESCE(c:voided::BOOLEAN, FALSE)),
          0::FLOAT,
          (acc, c) -> acc + COALESCE(c:amount::FLOAT, 0)
            - COALESCE(REDUCE(
                FILTER(c:selections, s -> NOT COALESCE(s:voided::BOOLEAN, FALSE)
                   AND s:selectionType::STRING IN (''TOAST_CARD_RELOAD'',''TOAST_CARD_SELL'',''GIFTCARD'',''STORED_VALUE_CARD'')),
                0::FLOAT, (a2, s) -> a2 + COALESCE(s:price::FLOAT, 0)
              ), 0)
        ) AS NET_AMOUNT,
        RAW_JSON:checks[0]:appliedDiscounts[0]:discount:name::STRING AS DISCOUNT_NAME,
        RAW_JSON:checks[0]:appliedDiscounts[0]:discountAmount::FLOAT AS DISCOUNT_AMOUNT,
        CASE WHEN ARRAY_SIZE(RAW_JSON:checks[0]:appliedDiscounts) > 0 THEN TRUE ELSE FALSE END AS HAS_DISCOUNT,
        RAW_JSON:checks[0]:payments[0]:type::STRING AS PAYMENT_TYPE,
        RAW_JSON:checks[0]:payments[0]:cardType::STRING AS CARD_TYPE,
        RAW_JSON:checks[0]:payments[0]:tipAmount::FLOAT AS TIP_AMOUNT,
        CASE WHEN ARRAY_SIZE(RAW_JSON:checks) > 1 THEN TRUE ELSE FALSE END AS IS_MULTI_CHECK,
        ARRAY_SIZE(RAW_JSON:checks) AS CHECK_COUNT,
        RAW_JSON:checks[0]:payments[0]:otherPayment:guid::STRING AS SERVER_GUID,
        INGESTED_AT, INGESTION_BATCH_ID
    FROM THREE_SISTERS_ANALYTICS.BRONZE.TOAST_ORDERS_RAW
    WHERE RAW_JSON:voided::BOOLEAN = FALSE AND RAW_JSON:deleted::BOOLEAN = FALSE
      AND RAW_JSON:paidDate::STRING IS NOT NULL;

    -- ---- Silver items (unchanged) ----
    CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDER_ITEMS_SILVER AS
    SELECT sel.value:guid::STRING AS SELECTION_GUID, RAW_JSON:guid::STRING AS ORDER_GUID,
        CONVERT_TIMEZONE(''UTC'',''America/New_York'', TRY_TO_TIMESTAMP_NTZ(RAW_JSON:paidDate::STRING,''YYYY-MM-DD"T"HH24:MI:SS.FF3TZHTZM''))::DATE AS BUSINESS_DATE,
        sel.value:displayName::STRING AS DISPLAY_NAME, sel.value:item:guid::STRING AS ITEM_GUID,
        sel.value:quantity::FLOAT AS QUANTITY, sel.value:price::FLOAT AS UNIT_PRICE,
        sel.value:receiptLinePrice::FLOAT AS RECEIPT_LINE_PRICE, sel.value:tax::FLOAT AS TAX,
        sel.value:voided::BOOLEAN AS VOIDED, sel.value:salesCategory:name::STRING AS SALES_CATEGORY,
        sel.value:appliedDiscounts[0]:discountAmount::FLOAT AS ITEM_DISCOUNT_AMOUNT, INGESTED_AT
    FROM THREE_SISTERS_ANALYTICS.BRONZE.TOAST_ORDERS_RAW,
        LATERAL FLATTEN(input => RAW_JSON:checks) chk,
        LATERAL FLATTEN(input => chk.value:selections) sel
    WHERE RAW_JSON:voided::BOOLEAN = FALSE AND RAW_JSON:deleted::BOOLEAN = FALSE
      AND sel.value:voided::BOOLEAN = FALSE AND RAW_JSON:paidDate::STRING IS NOT NULL;

    -- ---- Gold daily summary (unchanged) ----
    CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_SUMMARY AS
    WITH daily_sales AS (
        SELECT BUSINESS_DATE, COUNT(*) AS ORDER_COUNT, SUM(TOTAL_AMOUNT) AS GROSS_REVENUE, SUM(NET_AMOUNT) AS NET_REVENUE,
            SUM(TAX_AMOUNT) AS TOTAL_TAX, SUM(COALESCE(TIP_AMOUNT,0)) AS TOTAL_TIPS, SUM(COALESCE(DISCOUNT_AMOUNT,0)) AS TOTAL_DISCOUNTS,
            AVG(NET_AMOUNT) AS AVG_TICKET, SUM(CASE WHEN PAYMENT_TYPE=''CASH'' THEN NET_AMOUNT ELSE 0 END) AS CASH_REVENUE,
            SUM(CASE WHEN PAYMENT_TYPE=''CREDIT'' THEN NET_AMOUNT ELSE 0 END) AS CREDIT_REVENUE,
            COUNT(CASE WHEN HAS_DISCOUNT THEN 1 END) AS DISCOUNTED_ORDERS, MIN(OPENED_DATE) AS FIRST_ORDER_TIME, MAX(OPENED_DATE) AS LAST_ORDER_TIME
        FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDERS_SILVER GROUP BY BUSINESS_DATE
    ), daily_weather AS (
        SELECT DATE, MAX(TEMPERATURE_F) AS WEATHER_HIGH_F, MIN(TEMPERATURE_F) AS WEATHER_LOW_F, AVG(TEMPERATURE_F) AS WEATHER_AVG_F,
            SUM(PRECIPITATION_IN) AS TOTAL_PRECIP_IN, SUM(SNOWFALL_IN) AS TOTAL_SNOWFALL_IN, MODE(WEATHER_CATEGORY) AS WEATHER_CATEGORY,
            SUM(CASE WHEN SUNSHINE_DURATION_S>0 AND HOUR BETWEEN 9 AND 18 THEN 1 ELSE 0 END) AS SUNNY_HOURS,
            AVG(CASE WHEN HOUR BETWEEN 9 AND 18 THEN WIND_SPEED_MPH END) AS AVG_WIND_MPH
        FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY DATE,HOUR ORDER BY CASE WHEN DATA_TYPE=''archive'' THEN 0 ELSE 1 END) AS rn
              FROM THREE_SISTERS_ANALYTICS.BRONZE.WEATHER_HOURLY) WHERE rn=1 GROUP BY DATE
    )
    SELECT s.*, DAYOFWEEK(s.BUSINESS_DATE) AS DAY_OF_WEEK, DAYNAME(s.BUSINESS_DATE) AS DAY_NAME,
        (DAYOFWEEK(s.BUSINESS_DATE) IN (0,6)) AS IS_WEEKEND, (DAYOFWEEK(s.BUSINESS_DATE) IN (2,5)) AS IS_BREAD_DELIVERY_DAY,
        WEEKOFYEAR(s.BUSINESS_DATE) AS WEEK_OF_YEAR, MONTH(s.BUSINESS_DATE) AS MONTH_NUM,
        w.WEATHER_HIGH_F, w.WEATHER_LOW_F, w.WEATHER_AVG_F, w.TOTAL_PRECIP_IN, w.TOTAL_SNOWFALL_IN, w.WEATHER_CATEGORY, w.SUNNY_HOURS, w.AVG_WIND_MPH
    FROM daily_sales s LEFT JOIN daily_weather w ON s.BUSINESS_DATE = w.DATE;

    -- ---- Gold category (ITEM_CATALOG join + human overrides from the taxonomy
    -- review app; curated decisions in ITEM_CATEGORY_OVERRIDES always win) ----
    CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_BY_CATEGORY AS
    SELECT i.BUSINESS_DATE,
        COALESCE(c.CATEGORY_GROUP,''Uncategorized'') AS CATEGORY_GROUP,
        COALESCE(o.CATEGORY, c.CATEGORY, i.SALES_CATEGORY, ''Uncategorized'') AS SALES_CATEGORY,
        COUNT(*) AS ITEM_COUNT, SUM(i.RECEIPT_LINE_PRICE) AS CATEGORY_REVENUE,
        AVG(i.UNIT_PRICE) AS AVG_UNIT_PRICE, SUM(COALESCE(i.ITEM_DISCOUNT_AMOUNT,0)) AS CATEGORY_DISCOUNTS,
        COUNT_IF(c.ITEM_ID IS NULL) AS UNMATCHED_ITEM_LINES
    FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDER_ITEMS_SILVER i
    LEFT JOIN THREE_SISTERS_ANALYTICS.REFERENCE.ITEM_CATALOG c ON i.ITEM_GUID = c.ITEM_ID
    LEFT JOIN THREE_SISTERS_ANALYTICS.REFERENCE.ITEM_CATEGORY_OVERRIDES o ON i.ITEM_GUID = o.ITEM_ID
    WHERE i.VOIDED = FALSE GROUP BY 1,2,3;

    -- ---- Gold hourly (NEW) ----
    CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.GOLD.HOURLY_SALES_SUMMARY AS
    WITH order_hours AS (
        SELECT BUSINESS_DATE, HOUR(PAID_DATE) AS HOUR_OF_DAY, COUNT(*) AS ORDER_COUNT, SUM(NET_AMOUNT) AS NET_REVENUE,
               SUM(TOTAL_AMOUNT) AS GROSS_REVENUE, AVG(NET_AMOUNT) AS AVG_TICKET
        FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDERS_SILVER WHERE PAID_DATE IS NOT NULL GROUP BY 1,2
    ), date_spine AS (SELECT DISTINCT BUSINESS_DATE FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDERS_SILVER),
    store_hours AS (SELECT SEQ4() AS HOUR_OF_DAY FROM TABLE(GENERATOR(ROWCOUNT=>24)) WHERE SEQ4() BETWEEN 9 AND 19),
    spine AS (SELECT d.BUSINESS_DATE, s.HOUR_OF_DAY FROM date_spine d CROSS JOIN store_hours s
              UNION SELECT BUSINESS_DATE, HOUR_OF_DAY FROM order_hours),
    hw AS (SELECT DATE,HOUR,TEMPERATURE_F,PRECIPITATION_IN,WEATHER_CATEGORY,CLOUD_COVER_PCT FROM
           (SELECT *, ROW_NUMBER() OVER (PARTITION BY DATE,HOUR ORDER BY CASE WHEN DATA_TYPE=''archive'' THEN 0 ELSE 1 END) rn
            FROM THREE_SISTERS_ANALYTICS.BRONZE.WEATHER_HOURLY) WHERE rn=1)
    SELECT sp.BUSINESS_DATE, sp.HOUR_OF_DAY, COALESCE(o.ORDER_COUNT,0) AS ORDER_COUNT, COALESCE(o.NET_REVENUE,0) AS NET_REVENUE,
        COALESCE(o.GROSS_REVENUE,0) AS GROSS_REVENUE, o.AVG_TICKET, (sp.HOUR_OF_DAY BETWEEN 9 AND 19) AS IS_STORE_HOURS,
        (o.ORDER_COUNT IS NOT NULL) AS HAS_TRANSACTIONS, hw.TEMPERATURE_F AS WEATHER_TEMP_F, hw.PRECIPITATION_IN AS PRECIP_IN,
        hw.WEATHER_CATEGORY, hw.CLOUD_COVER_PCT, DAYNAME(sp.BUSINESS_DATE) AS DAY_NAME, (DAYOFWEEK(sp.BUSINESS_DATE) IN (0,6)) AS IS_WEEKEND
    FROM spine sp LEFT JOIN order_hours o ON sp.BUSINESS_DATE=o.BUSINESS_DATE AND sp.HOUR_OF_DAY=o.HOUR_OF_DAY
    LEFT JOIN hw ON sp.BUSINESS_DATE=hw.DATE AND sp.HOUR_OF_DAY=hw.HOUR;

    RETURN ''Transforms refreshed (silver, daily, category[fixed], hourly)'';
END;
';