-- REFRESH_DQ: rebuilds all 8 DQ tables from ITEM_CATALOG + sales velocity.
-- Mirrors Databricks dq schema. Full-replace snapshots; safe to re-run.
CREATE OR REPLACE PROCEDURE THREE_SISTERS_ANALYTICS.DQ.REFRESH_DQ()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
  -- Shared velocity CTEs are recomputed per table via a helper view for clarity.
  CREATE OR REPLACE VIEW THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY AS
  WITH s60 AS (
    SELECT ITEM_GUID,
           COUNT(DISTINCT BUSINESS_DATE) AS selling_days_60d,
           ROUND(SUM(QUANTITY)/60.0, 3) AS avg_daily_units_60d,
           SUM(RECEIPT_LINE_PRICE) AS revenue_60d,
           MAX(BUSINESS_DATE) AS last_sold_60d
    FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDER_ITEMS_SILVER
    WHERE VOIDED = FALSE AND QUANTITY > 0 AND BUSINESS_DATE >= DATEADD('day',-60,CURRENT_DATE())
    GROUP BY ITEM_GUID
  ),
  s90 AS (
    SELECT ITEM_GUID, ROUND(SUM(QUANTITY)/90.0,3) AS avg_daily_units_90d
    FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDER_ITEMS_SILVER
    WHERE VOIDED = FALSE AND QUANTITY > 0 AND BUSINESS_DATE >= DATEADD('day',-90,CURRENT_DATE())
    GROUP BY ITEM_GUID
  ),
  alltime AS (
    SELECT ITEM_GUID, MAX(BUSINESS_DATE) AS last_sold_alltime
    FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDER_ITEMS_SILVER
    WHERE VOIDED = FALSE AND QUANTITY > 0
    GROUP BY ITEM_GUID
  )
  SELECT ic.*,
         COALESCE(s60.selling_days_60d,0) AS selling_days_60d,
         COALESCE(s60.avg_daily_units_60d,0.0) AS avg_daily_units_60d,
         COALESCE(s60.revenue_60d,0.0) AS revenue_60d,
         COALESCE(s90.avg_daily_units_90d,0.0) AS avg_daily_units_90d,
         COALESCE(s60.last_sold_60d, alltime.last_sold_alltime) AS last_sold_date,
         TRY_TO_DOUBLE(NULLIF(TRIM(ic.INVENTORY_QUANTITY),'')) AS qty_on_hand_num
  FROM THREE_SISTERS_ANALYTICS.REFERENCE.ITEM_CATALOG ic
  LEFT JOIN s60 ON ic.ITEM_ID = s60.ITEM_GUID
  LEFT JOIN s90 ON ic.ITEM_ID = s90.ITEM_GUID
  LEFT JOIN alltime ON ic.ITEM_ID = alltime.ITEM_GUID;

  -- 1. PAR_LEVEL_SUGGESTIONS (active items; par computed from 7d/14d velocity if blank)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.PAR_LEVEL_SUGGESTIONS AS
  SELECT NAME, BARCODE, PLU, CATEGORY_GROUP, CATEGORY, SUPPLIER,
         qty_on_hand_num AS QTY_ON_HAND,
         CASE WHEN qty_on_hand_num IS NULL THEN 'not tracked'
              WHEN qty_on_hand_num > 0 THEN 'in stock' ELSE 'out of stock' END AS INVENTORY_STATUS,
         avg_daily_units_60d AS AVG_DAILY_UNITS_60D, selling_days_60d AS SELLING_DAYS_60D, last_sold_date AS LAST_SOLD_DATE,
         RECEIVING_UNITS, RECEIVING_UNIT_QUANTITIES,
         CASE WHEN TRIM(COALESCE(PAR_MIN,''))<>'' THEN PAR_MIN
              WHEN avg_daily_units_60d>0 THEN CAST(CEIL(7*avg_daily_units_60d) AS STRING) ELSE '' END AS PAR_MIN,
         CASE WHEN TRIM(COALESCE(PAR_MAX,''))<>'' THEN PAR_MAX
              WHEN avg_daily_units_60d>0 THEN CAST(CEIL(14*avg_daily_units_60d) AS STRING) ELSE '' END AS PAR_MAX,
         CURRENT_TIMESTAMP() AS _REFRESHED_AT
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY WHERE IS_DISCONTINUED = FALSE;

  -- 2. MISSING_COST (active, no cost, but selling)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.MISSING_COST AS
  SELECT NAME, BARCODE, PLU, CATEGORY_GROUP, CATEGORY, SUPPLIER, PRICE, LAST_SOLD_DATE,
         AVG_DAILY_UNITS_60D, REVENUE_60D, COST
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE IS_DISCONTINUED = FALSE AND COST IS NULL AND revenue_60d > 0;

  -- 3. MISSING_SUPPLIER (active, no supplier)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.MISSING_SUPPLIER AS
  SELECT NAME, BARCODE, PLU, CATEGORY_GROUP, CATEGORY, BRAND, qty_on_hand_num AS QTY_ON_HAND,
         CASE WHEN qty_on_hand_num IS NULL THEN 'not tracked' WHEN qty_on_hand_num>0 THEN 'in stock' ELSE 'out of stock' END AS INVENTORY_STATUS,
         PRICE, LAST_SOLD_DATE, AVG_DAILY_UNITS_60D, SUPPLIER, SUPPLIER_ITEM_ID
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE IS_DISCONTINUED = FALSE AND (SUPPLIER IS NULL OR TRIM(SUPPLIER)='');

  -- 4. MISSING_BARCODE (active, no barcode)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.MISSING_BARCODE AS
  SELECT NAME, PLU, CATEGORY_GROUP, CATEGORY, BRAND, SUPPLIER, SUPPLIER_ITEM_ID, PRICE, LAST_SOLD_DATE,
         AVG_DAILY_UNITS_90D, ROUND(AVG_DAILY_UNITS_90D*7,2) AS EST_WEEKLY_UNITS, BARCODE
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE IS_DISCONTINUED = FALSE AND (BARCODE IS NULL OR TRIM(BARCODE)='');

  -- 5. CATEGORY_DRIFT (sales_category <> category)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.CATEGORY_DRIFT AS
  SELECT NAME, BARCODE, PLU, CATEGORY_GROUP, CATEGORY AS CORRECT_CATEGORY, SALES_CATEGORY AS CURRENT_SALES_CATEGORY, PRICE, SUPPLIER
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE CATEGORY_DRIFT = TRUE;

  -- 6. SUGGESTED_DISCONTINUED (active but no sale in 90d)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.SUGGESTED_DISCONTINUED AS
  SELECT NAME, BARCODE, PLU, CATEGORY_GROUP, CATEGORY, SUPPLIER, qty_on_hand_num AS QTY_ON_HAND, PRICE, LAST_SOLD_DATE,
         DATEDIFF('day', LAST_SOLD_DATE, CURRENT_DATE())::INT AS DAYS_SINCE_LAST_SALE,
         AVG_DAILY_UNITS_60D, IS_DISCONTINUED, DISCONTINUED_REASON
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE IS_DISCONTINUED = FALSE
    AND (LAST_SOLD_DATE IS NULL OR LAST_SOLD_DATE < DATEADD('day',-90,CURRENT_DATE()));

  -- 7. INVERTED_MARGIN (cost >= price)
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.INVERTED_MARGIN AS
  SELECT NAME, BARCODE, PLU, CATEGORY_GROUP, CATEGORY, SUPPLIER, PRICE, COST, GROSS_MARGIN,
         ROUND((PRICE-COST)/NULLIF(PRICE,0)*100,2) AS CALCULATED_MARGIN_PCT,
         ROUND((COST-PRICE)*AVG_DAILY_UNITS_60D,2) AS EST_DAILY_LOSS_USD,
         REVENUE_60D, NULL::DOUBLE AS COST_CORRECTED, NULL::DOUBLE AS PRICE_CORRECTED
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE COST IS NOT NULL AND PRICE IS NOT NULL AND COST >= PRICE AND PRICE > 0;

  -- 8. NOMENCLATURE_FIX (all-caps or trailing/leading whitespace names) -- heuristic
  CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.DQ.NOMENCLATURE_FIX AS
  SELECT NAME AS CURRENT_NAME, BARCODE, PLU, BRAND, CATEGORY_GROUP, CATEGORY, PRICE,
         INITCAP(TRIM(NAME)) AS SUGGESTED_NAME,
         (NAME <> INITCAP(TRIM(NAME))) AS AUTO_FIX_CANDIDATE,
         NAME
  FROM THREE_SISTERS_ANALYTICS.DQ.V_ITEM_VELOCITY
  WHERE NAME IS NOT NULL AND NAME <> INITCAP(TRIM(NAME));

  RETURN 'DQ refreshed: par_levels, missing_cost/supplier/barcode, category_drift, suggested_discontinued, inverted_margin, nomenclature_fix';
END;
$$;

CALL THREE_SISTERS_ANALYTICS.DQ.REFRESH_DQ();
