-- Rebuild DAILY_SALES_BY_CATEGORY with real categories via ITEM_CATALOG join.
-- Grain: business_date x category_group x category (mirrors Databricks NB4).
CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_BY_CATEGORY AS
SELECT
    i.BUSINESS_DATE,
    COALESCE(c.CATEGORY_GROUP, 'Uncategorized') AS CATEGORY_GROUP,
    COALESCE(c.CATEGORY, i.SALES_CATEGORY, 'Uncategorized') AS SALES_CATEGORY,
    COUNT(*) AS ITEM_COUNT,
    SUM(i.RECEIPT_LINE_PRICE) AS CATEGORY_REVENUE,
    AVG(i.UNIT_PRICE) AS AVG_UNIT_PRICE,
    SUM(COALESCE(i.ITEM_DISCOUNT_AMOUNT, 0)) AS CATEGORY_DISCOUNTS,
    COUNT_IF(c.ITEM_ID IS NULL) AS UNMATCHED_ITEM_LINES
FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDER_ITEMS_SILVER i
LEFT JOIN THREE_SISTERS_ANALYTICS.REFERENCE.ITEM_CATALOG c
       ON i.ITEM_GUID = c.ITEM_ID
WHERE i.VOIDED = FALSE
GROUP BY 1, 2, 3
ORDER BY 1, CATEGORY_REVENUE DESC;

SELECT COUNT(*) AS rows_total,
       COUNT(DISTINCT SALES_CATEGORY) AS distinct_categories,
       SUM(CASE WHEN SALES_CATEGORY='Uncategorized' THEN ITEM_COUNT ELSE 0 END) AS uncat_item_lines,
       SUM(ITEM_COUNT) AS total_item_lines
FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_BY_CATEGORY;
