-- ============================================================================
-- 1. Add run-history columns to DAILY_SALES_FORECAST (keep every run, not just latest)
-- ============================================================================
ALTER TABLE THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST
  ADD COLUMN IF NOT EXISTS FORECAST_CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST
  ADD COLUMN IF NOT EXISTS FORECAST_HORIZON_DAYS NUMBER;

-- Backfill created_at from generated_at for existing rows
UPDATE THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST
  SET FORECAST_CREATED_AT = GENERATED_AT
  WHERE FORECAST_CREATED_AT IS NULL;

-- ============================================================================
-- 2. Forecast accuracy history table (parity with DBX gold.forecast_accuracy_history)
-- ============================================================================
CREATE TABLE IF NOT EXISTS THREE_SISTERS_ANALYTICS.GOLD.FORECAST_ACCURACY_HISTORY (
  EVALUATED_AT TIMESTAMP_NTZ,
  MODEL_VERSION STRING,
  HORIZON_DAYS NUMBER,       -- 1,7,14,30 : how far ahead the forecast was made
  N_DAYS_SCORED NUMBER,
  MAPE FLOAT,                -- mean abs pct error on realized actuals
  BIAS_PCT FLOAT,            -- mean (forecast-actual)/actual
  METRIC STRING              -- 'revenue' or 'orders'
) COMMENT='One row per (eval run, horizon, metric). Tracks realized forecast accuracy vs actuals.';

-- ============================================================================
-- 3. Rebuild REFRESH_FORECASTS: keep run history + stamp created_at/horizon
-- ============================================================================
CREATE OR REPLACE PROCEDURE THREE_SISTERS_ANALYTICS.GOLD.REFRESH_FORECASTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
  v_version VARCHAR;
  v_training_days NUMBER;
  v_now TIMESTAMP_NTZ;
BEGIN
  v_now := CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
  v_version := 'snowflake_ml_v' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD');

  -- Retrain models on latest data
  CREATE OR REPLACE SNOWFLAKE.ML.FORECAST THREE_SISTERS_ANALYTICS.GOLD.REVENUE_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'THREE_SISTERS_ANALYTICS.GOLD.V_FORECAST_TRAINING'),
    TIMESTAMP_COLNAME => 'BUSINESS_DATE',
    TARGET_COLNAME => 'NET_REVENUE'
  );
  CREATE OR REPLACE SNOWFLAKE.ML.FORECAST THREE_SISTERS_ANALYTICS.GOLD.ORDER_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'THREE_SISTERS_ANALYTICS.GOLD.V_ORDER_FORECAST_TRAINING'),
    TIMESTAMP_COLNAME => 'BUSINESS_DATE',
    TARGET_COLNAME => 'ORDER_COUNT'
  );

  -- Replace ONLY this version's future rows (idempotent same-day rerun),
  -- but KEEP prior runs so accuracy-by-horizon history survives.
  DELETE FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST
    WHERE MODEL_VERSION = :v_version AND FORECAST_DATE >= CURRENT_DATE();

  CREATE OR REPLACE TEMPORARY TABLE THREE_SISTERS_ANALYTICS.GOLD.TMP_REVENUE_FC AS
    SELECT TS::DATE AS FORECAST_DATE, FORECAST AS FORECAST_REVENUE, LOWER_BOUND AS YHAT_LOWER, UPPER_BOUND AS YHAT_UPPER
    FROM TABLE(THREE_SISTERS_ANALYTICS.GOLD.REVENUE_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 30));
  CREATE OR REPLACE TEMPORARY TABLE THREE_SISTERS_ANALYTICS.GOLD.TMP_ORDER_FC AS
    SELECT TS::DATE AS DT, ROUND(FORECAST) AS FORECAST_ORDERS
    FROM TABLE(THREE_SISTERS_ANALYTICS.GOLD.ORDER_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 30));

  INSERT INTO THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST
    (FORECAST_DATE, FORECAST_REVENUE, FORECAST_ORDERS, YHAT_LOWER, YHAT_UPPER, MODEL_VERSION, GENERATED_AT,
     FORECAST_CREATED_AT, FORECAST_HORIZON_DAYS)
  SELECT r.FORECAST_DATE, r.FORECAST_REVENUE, o.FORECAST_ORDERS, r.YHAT_LOWER, r.YHAT_UPPER,
         :v_version, :v_now, :v_now, DATEDIFF('day', CURRENT_DATE(), r.FORECAST_DATE)
  FROM THREE_SISTERS_ANALYTICS.GOLD.TMP_REVENUE_FC r
  LEFT JOIN THREE_SISTERS_ANALYTICS.GOLD.TMP_ORDER_FC o ON r.FORECAST_DATE = o.DT;

  SELECT COUNT(DISTINCT BUSINESS_DATE) INTO :v_training_days
    FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_SUMMARY WHERE NET_REVENUE > 0;

  INSERT INTO THREE_SISTERS_ANALYTICS.GOLD.MODEL_RUNS
    (MODEL_NAME, MODEL_VERSION, TRAINING_DAYS, FORECAST_HORIZON, STATUS)
  VALUES ('revenue_forecast', :v_version, :v_training_days, 30, 'SUCCESS');

  DROP TABLE IF EXISTS THREE_SISTERS_ANALYTICS.GOLD.TMP_REVENUE_FC;
  DROP TABLE IF EXISTS THREE_SISTERS_ANALYTICS.GOLD.TMP_ORDER_FC;

  RETURN 'Forecasts refreshed (history-preserving): ' || :v_version || ' (' || :v_training_days || ' training days)';
END;
$$;

-- ============================================================================
-- 4. Fix PLATINUM.DAILY_SALES_COMBINED: actuals UNION latest-run forecasts (future only)
-- ============================================================================
CREATE OR REPLACE VIEW THREE_SISTERS_ANALYTICS.PLATINUM.DAILY_SALES_COMBINED AS
WITH latest_actual AS (
  SELECT MAX(BUSINESS_DATE) AS max_actual_date
  FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_SUMMARY WHERE NET_REVENUE > 0
),
latest_run AS (
  SELECT MAX(FORECAST_CREATED_AT) AS max_run FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST
)
SELECT
    BUSINESS_DATE, ORDER_COUNT, GROSS_REVENUE, NET_REVENUE, TOTAL_TAX, TOTAL_TIPS, AVG_TICKET,
    DAY_NAME, IS_WEEKEND, IS_BREAD_DELIVERY_DAY, WEATHER_HIGH_F, WEATHER_CATEGORY, TOTAL_PRECIP_IN, SUNNY_HOURS,
    NULL::FLOAT AS FORECAST_LOWER, NULL::FLOAT AS FORECAST_UPPER,
    'actual' AS RECORD_TYPE
FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_SUMMARY
UNION ALL
SELECT
    f.FORECAST_DATE AS BUSINESS_DATE, f.FORECAST_ORDERS AS ORDER_COUNT,
    NULL AS GROSS_REVENUE, f.FORECAST_REVENUE AS NET_REVENUE, NULL AS TOTAL_TAX, NULL AS TOTAL_TIPS, NULL AS AVG_TICKET,
    DAYNAME(f.FORECAST_DATE) AS DAY_NAME,
    (DAYOFWEEK(f.FORECAST_DATE) IN (0,6)) AS IS_WEEKEND,
    (DAYOFWEEK(f.FORECAST_DATE) IN (2,5)) AS IS_BREAD_DELIVERY_DAY,
    NULL AS WEATHER_HIGH_F, NULL AS WEATHER_CATEGORY, NULL AS TOTAL_PRECIP_IN, NULL AS SUNNY_HOURS,
    f.YHAT_LOWER AS FORECAST_LOWER, f.YHAT_UPPER AS FORECAST_UPPER,
    'forecast' AS RECORD_TYPE
FROM THREE_SISTERS_ANALYTICS.GOLD.DAILY_SALES_FORECAST f, latest_actual a, latest_run r
WHERE f.FORECAST_CREATED_AT = r.max_run       -- only the newest run
  AND f.FORECAST_DATE > a.max_actual_date;     -- only dates beyond actuals (no double-count)

SELECT 'forecast+platinum rebuilt' AS status;
