-- HOURLY_SALES_SUMMARY: 1 row per (business_date, hour_of_day).
-- Hour spine = store hours 9..19 ET UNION any hour with transactions, per NB4.
CREATE OR REPLACE TABLE THREE_SISTERS_ANALYTICS.GOLD.HOURLY_SALES_SUMMARY AS
WITH order_hours AS (
    SELECT BUSINESS_DATE, HOUR(PAID_DATE) AS HOUR_OF_DAY,
           COUNT(*) AS ORDER_COUNT, SUM(NET_AMOUNT) AS NET_REVENUE,
           SUM(TOTAL_AMOUNT) AS GROSS_REVENUE, AVG(NET_AMOUNT) AS AVG_TICKET
    FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDERS_SILVER
    WHERE PAID_DATE IS NOT NULL
    GROUP BY BUSINESS_DATE, HOUR(PAID_DATE)
),
date_spine AS (
    SELECT DISTINCT BUSINESS_DATE FROM THREE_SISTERS_ANALYTICS.SILVER_SALES.ORDERS_SILVER
),
store_hours AS (
    SELECT h.HOUR_OF_DAY FROM (SELECT SEQ4() AS HOUR_OF_DAY FROM TABLE(GENERATOR(ROWCOUNT => 24))) h
    WHERE h.HOUR_OF_DAY BETWEEN 9 AND 19
),
spine AS (
    -- store hours for every business date
    SELECT d.BUSINESS_DATE, s.HOUR_OF_DAY FROM date_spine d CROSS JOIN store_hours s
    UNION
    -- any transaction hour outside store hours
    SELECT BUSINESS_DATE, HOUR_OF_DAY FROM order_hours
),
hourly_weather AS (
    SELECT DATE, HOUR, TEMPERATURE_F, PRECIPITATION_IN, WEATHER_CATEGORY, CLOUD_COVER_PCT
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY DATE, HOUR ORDER BY CASE WHEN DATA_TYPE='archive' THEN 0 ELSE 1 END) rn
        FROM THREE_SISTERS_ANALYTICS.BRONZE.WEATHER_HOURLY
    ) WHERE rn = 1
)
SELECT
    sp.BUSINESS_DATE, sp.HOUR_OF_DAY,
    COALESCE(o.ORDER_COUNT, 0) AS ORDER_COUNT,
    COALESCE(o.NET_REVENUE, 0) AS NET_REVENUE,
    COALESCE(o.GROSS_REVENUE, 0) AS GROSS_REVENUE,
    o.AVG_TICKET,
    (sp.HOUR_OF_DAY BETWEEN 9 AND 19) AS IS_STORE_HOURS,
    (o.ORDER_COUNT IS NOT NULL) AS HAS_TRANSACTIONS,
    w.TEMPERATURE_F AS WEATHER_TEMP_F, w.PRECIPITATION_IN AS PRECIP_IN,
    w.WEATHER_CATEGORY, w.CLOUD_COVER_PCT,
    DAYNAME(sp.BUSINESS_DATE) AS DAY_NAME,
    (DAYOFWEEK(sp.BUSINESS_DATE) IN (0,6)) AS IS_WEEKEND
FROM spine sp
LEFT JOIN order_hours o ON sp.BUSINESS_DATE = o.BUSINESS_DATE AND sp.HOUR_OF_DAY = o.HOUR_OF_DAY
LEFT JOIN hourly_weather w ON sp.BUSINESS_DATE = w.DATE AND sp.HOUR_OF_DAY = w.HOUR
ORDER BY sp.BUSINESS_DATE, sp.HOUR_OF_DAY;

SELECT COUNT(*) rows, COUNT(DISTINCT BUSINESS_DATE) days,
       ROUND(SUM(NET_REVENUE),0) total_net, COUNT_IF(HAS_TRANSACTIONS) txn_hours
FROM THREE_SISTERS_ANALYTICS.GOLD.HOURLY_SALES_SUMMARY;
